import type { AppData } from "./types";
import { DEFAULT_ZONES } from "./types";

export const initialData: AppData = {
  zones: [...DEFAULT_ZONES],
  students: [
    {
      id: "st-carlos",
      name: "Carlos Santana",
      phone: "+34 628 114 902",
      startDate: "2026-06-02T09:00:00.000Z",
      avatarColor: "oklch(0.62 0.17 250)",
      skills: {
        volante: "verde",
        pedales: "verde",
        marchas: "amarillo",
        observacion: "amarillo",
        glorietas: "rojo",
        estacionamiento: "amarillo",
      },
      lessons: [
        {
          id: "ls-c1",
          number: 1,
          date: "2026-06-02T09:00:00.000Z",
          zone: "Vecindario",
          topics: ["Volante", "Pedales"],
          notes: "Primer contacto con el coche. Arranques y paradas suaves.",
        },
        {
          id: "ls-c2",
          number: 2,
          date: "2026-06-09T09:00:00.000Z",
          zone: "Vecindario",
          topics: ["Marchas", "Pedales"],
          notes: "Mejora en los cambios de marcha, todavía cala en cuestas.",
        },
        {
          id: "ls-c3",
          number: 3,
          date: "2026-06-16T17:30:00.000Z",
          zone: "Cruce de Arinaga",
          topics: ["Observación", "Incorporaciones"],
          notes: "Necesita mejorar la observación en cruces.",
        },
        {
          id: "ls-c4",
          number: 4,
          date: "2026-06-23T17:30:00.000Z",
          zone: "Las Palmas",
          topics: ["Glorietas", "Cambios de carril"],
          notes: "Muy nervioso en glorietas, repetir la próxima clase.",
        },
      ],
    },
    {
      id: "st-laura",
      name: "Laura Morales",
      phone: "+34 610 552 388",
      startDate: "2026-03-11T16:00:00.000Z",
      avatarColor: "oklch(0.6 0.16 25)",
      skills: {
        volante: "verde",
        pedales: "verde",
        marchas: "verde",
        observacion: "verde",
        glorietas: "amarillo",
        estacionamiento: "amarillo",
      },
      lessons: [
        {
          id: "ls-l1",
          number: 1,
          date: "2026-03-11T16:00:00.000Z",
          zone: "Vecindario",
          topics: ["Volante", "Pedales", "Marchas"],
          notes: "Base sólida desde el primer día.",
        },
        {
          id: "ls-l2",
          number: 2,
          date: "2026-03-18T16:00:00.000Z",
          zone: "Las Palmas",
          topics: ["Glorietas", "Observación"],
          notes: "Buena progresión, más segura al volante.",
        },
        {
          id: "ls-l3",
          number: 3,
          date: "2026-03-25T16:00:00.000Z",
          zone: "Zona de Examen",
          topics: ["Aparcamiento", "Marcha atrás"],
          notes: "Aparcamiento en línea casi dominado.",
        },
        {
          id: "ls-l4",
          number: 4,
          date: "2026-04-02T18:00:00.000Z",
          zone: "Zona de Examen",
          topics: ["Observación", "Glorietas"],
          notes: "Clase muy completa, lista para zona de examen.",
        },
        {
          id: "ls-l5",
          number: 5,
          date: "2026-04-09T18:00:00.000Z",
          zone: "Cruce de Arinaga",
          topics: ["Incorporaciones", "Autovía"],
          notes: "Segura en autovía, mantener ritmo.",
        },
      ],
    },
    {
      id: "st-ayoze",
      name: "Ayoze Peña",
      phone: "+34 677 231 045",
      startDate: "2026-08-20T11:00:00.000Z",
      avatarColor: "oklch(0.62 0.15 150)",
      skills: {
        volante: "amarillo",
        pedales: "rojo",
        marchas: "rojo",
        observacion: "amarillo",
        glorietas: "rojo",
        estacionamiento: "rojo",
      },
      lessons: [
        {
          id: "ls-a1",
          number: 1,
          date: "2026-08-20T11:00:00.000Z",
          zone: "Vecindario",
          topics: ["Volante", "Pedales"],
          notes: "Le cuesta coordinar embrague y acelerador.",
        },
        {
          id: "ls-a2",
          number: 2,
          date: "2026-08-27T11:00:00.000Z",
          zone: "Vecindario",
          topics: ["Pedales", "Marchas"],
          notes: "Repetir maniobras básicas en zona tranquila.",
        },
      ],
    },
  ],
};
