/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGestionRouteImport } from './routes/_authenticated/gestion'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAlumnoStudentIdRouteImport } from './routes/_authenticated/alumno.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestionRoute = AuthenticatedGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlumnoStudentIdRoute =
  AuthenticatedAlumnoStudentIdRouteImport.update({
    id: '/alumno/$studentId',
    path: '/alumno/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/alumno/$studentId': typeof AuthenticatedAlumnoStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/alumno/$studentId': typeof AuthenticatedAlumnoStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/gestion': typeof AuthenticatedGestionRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/alumno/$studentId': typeof AuthenticatedAlumnoStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/politica-cookies'
    | '/privacidad'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/gestion'
    | '/panel'
    | '/.lovable/oauth/consent'
    | '/alumno/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/politica-cookies'
    | '/privacidad'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/gestion'
    | '/panel'
    | '/.lovable/oauth/consent'
    | '/alumno/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/politica-cookies'
    | '/privacidad'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/gestion'
    | '/_authenticated/panel'
    | '/.lovable/oauth/consent'
    | '/_authenticated/alumno/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestion': {
      id: '/_authenticated/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof AuthenticatedGestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alumno/$studentId': {
      id: '/_authenticated/alumno/$studentId'
      path: '/alumno/$studentId'
      fullPath: '/alumno/$studentId'
      preLoaderRoute: typeof AuthenticatedAlumnoStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGestionRoute: typeof AuthenticatedGestionRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedAlumnoStudentIdRoute: typeof AuthenticatedAlumnoStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGestionRoute: AuthenticatedGestionRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedAlumnoStudentIdRoute: AuthenticatedAlumnoStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
